services:
  db:
    image: postgres:17
    container_name: invoice_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: invoicer
      POSTGRES_PASSWORD: invoicer_pw
      POSTGRES_DB: invoicedb
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
